interface ApiToken {
    id: string;
    symbol: string;
    name: string;
    image: string;
    current_price: number;
    market_cap: number;
    market_cap_rank: number;
    fully_diluted_valuation: number;
    total_volume: number;
    high_24h: number;
    low_24h: number;
    price_change_24h: number;
    price_change_percentage_24h: number;
    market_cap_change_24h: number;
    market_cap_change_percentage_24h: number;
    circulating_supply: number;
    total_supply: number;
    max_supply: number;
    ath: number;
    ath_change_percentage: number;
    ath_date: string;
    atl: number;
    atl_change_percentage: number;
    atl_date: string;
    roi: number | null;
    last_updated: string;
    error?: string;
};

// interface ApiToken {
//   id: string;
//   symbol: string;
//   name: string;
//   image: string;
//   currentPrice: number;
//   marketCap: number;
//   marketCapRank: number;
//   fullyDilutedValuation: number;
//   totalVolume: number;
//   high24h: number;
//   low24h: number;
//   priceChange24h: number;
//   priceChangePercentage_24h: number;
//   marketCapChange24h: number;
//   marketCapChangePercentage_24h: number;
//   circulatingSupply: number;
//   totalSupply: number;
//   maxSupply: number;
//   ath: number;
//   athChangePercentage: number;
//   athDate: string;
//   atl: number;
//   atlChangePercentage: number;
//   atlDate: string;
//   roi: number | null;
//   lastUpdated: string;
//   error?: string;
// };

